config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :users
  resources :companies
  resources :jobs
  resources :sessions

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/about-us" => "static_pages#about-us"

  get 'auth/:provider/callback', to: 'static_pages#index'

  

end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user

	validates :address1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true
	validates :user, presence: true

	def full_address
	 	unless address2.blank?
	 		"#{address1}\n#{address2}\n #{city}, #{state}. #{zip}"
	 	else
	 		"#{address1}\n #{city}, #{state}. #{zip}"
	 	end
	end
end

app/models/company.rb
class Company < ActiveRecord::Base

	belongs_to :user
	belongs_to :type
	belongs_to :sector
	has_many :jobs
	has_and_belongs_to_many :vet_programs

	accepts_nested_attributes_for :type, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :vet_programs, reject_if: :all_blank, allow_destroy: true

	validates :name, presence: true
	validates :address1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true
	validates :website, presence: true
	validates :num_employees, presence: true
	validates :description, presence: true
	validates :contact_name, presence: true
	validates :contact_position, presence: true
	validates :contact_email, presence: true	
	validates :contact_phone, presence: true
	validates :verified, inclusion: { in: [true, false] }

end

app/models/education.rb
class Education < ActiveRecord::Base

	belongs_to :user

	validates :school_name, presence: true
	validates :user, presence: true	
end

app/models/employment_type.rb
class EmploymentType < ActiveRecord::Base

	has_many :jobs

	validates :name, presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base

	has_many :jobs

	validates :name, presence: true
end

app/models/job.rb
class Job < ActiveRecord::Base
	
	belongs_to :company
	belongs_to :employment_type
	belongs_to :experience
	belongs_to :jobfunction
	belongs_to :status

	has_and_belongs_to_many :skills

	accepts_nested_attributes_for :status, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :company, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :jobfunction, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :experience, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true	

	validates :title, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :description, presence: true
	validates :salary, presence: true
	validates :company, presence: true
	validates :employment_type, presence: true
	validates :experience, presence: true
	validates :jobfunction, presence: true
	validates :status, presence: true

end

app/models/jobfunction.rb
class Jobfunction < ActiveRecord::Base

	has_many :jobs

	validates :name, presence: true
end

app/models/military_experience.rb
class MilitaryExperience < ActiveRecord::Base

	belongs_to :user

	validates :user, presence: true
	validates :branch, presence: true
	validates :mos, presence: true
	
end

app/models/sector.rb
class Sector < ActiveRecord::Base

	has_many :companies

	validates :name, presence: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	
	has_and_belongs_to_many :jobs
	has_and_belongs_to_many :users

	validates :name, presence: true

end

app/models/skill_user.rb
class Skill_User < ActiveRecord::Base

end

app/models/status.rb
class Status < ActiveRecord::Base

	has_many :jobs

	validates :name, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
	
	has_many :companies

	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_one :military_experience
	has_one :address
	has_one :company
	has_many :educations
	has_many :work_histories
	has_and_belongs_to_many :skills

	mount_uploader :avatar, AvatarUploader

	accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :work_histories, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :military_experience, reject_if: :all_blank, allow_destroy: true

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :verified, inclusion: { in: [true, false] }
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

end

app/models/vet_program.rb
class VetProgram < ActiveRecord::Base
	has_and_belongs_to_many :companies

	validates :name, presence: true
end

app/models/work_history.rb
class WorkHistory < ActiveRecord::Base

	belongs_to :user

	validates :company_name, presence: true
	validates :job_title, presence: true

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.all
  end

  def new
    @job = current_user.company.jobs.new
    # @employment_types = EmploymentType.all
    @job.build_employment_type
    @job.build_status
    @job.build_jobfunction
    @job.build_experience
  end

  def create
    @job = current_user.company.jobs.new(jobs_params)
  	if @job.save
  		flash[:notice] = "Job successfully created!"
  		redirect_to @job
  	else
  		render :new
  	end
  end

  def edit
  	@job = Job.find(params[:id])
  end

  def update
  	@job = Job.find(params[:id])

  	if @job.update(jobs_params)
  		flash[:notice] = "This job has been updated"
  		redirect_to @job
  	else
  		render :edit
  	end
  end

  def show
  	@job = Job.find(params[:id])
  end

  private
  	def jobs_params
  		params.require(:job).permit(:title, :city, :state, :description, :salary, :employment_type_id, :experience_id, :status_id, :jobfunction_id, :user_id, :company_id, :company, skills_attributes: [:id, :name, :_destroy])
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def new
		@user = User.new
		@submit_message = 'Sign Up'
		@veteran_message = 'Sign Up As A Veteran'
		@business_message = 'Sign Up As A Company'
	end

	def show 
		@user = User.find(params[:id])
		@company = @user.company
		@name = [@user.first_name,@user.last_name].join(' ').squeeze(' ')
		@test = request.env['omniauth.auth']
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "User successfully created!"
			redirect_to user_path(@user)
		else
			render :new

		end
	end

	def edit
		@user = User.find(params[:id])
		@user.build_address if @user.address.blank?
		@user.build_military_experience if @user.military_experience.blank?
		@veteran_message = 'Update Account'
		@submit_message = 'Update Account'
	end

	def post
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			flash[:notice] = "This user has been updated."
			redirect_to @user
		else
			render :edit
		end
	end 

	def destroy 
		User.find(params[:id]).destroy
		flash[:notice]= "User has been deleted."
		session.delete(:user_id)
		redirect_to root_path
	end 

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, 
				:email, :password, :password_confirmation, :business, :avatar,
				educations_attributes: [:id, :school_name, :yr_attended_from,
			 		:yr_attended_to, :degree_name, :field_of_study, :description, :_destroy],
		 		work_histories_attributes: [:id, :company_name, :job_title, :location, 
		 			:start_date, :end_date, :description, :_destroy],
	 			skills_attributes: [:id, :name, :_destroy ],
	 			address_attributes: [:id, :address1, :address2, :city, :state, :zip, :_destroy],
	 			military_experience_attributes: [:id, :branch, :mos, :start_date, :end_date, :_destroy])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end

	def current_user_is_business?
		current_user.business
	end

	def current_user_is_veteran?
		!current_user.business
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_company_fields.html.slim
.nested-fields
	.field
		= f.hidden_field :id, class: "form-control"

app/views/jobs/_employment_type_fields.html.slim
.nested-fields
	.field
	  = f.label "Employment Type"
    = collection_select(:job, :employment_type_id, EmploymentType.all, :id, :name)

app/views/jobs/_experience_fields.html.slim
.nested-fields
	.field
	  = f.label "Experience Level"
    = collection_select(:job, :experience_id, Experience.all, :id, :name)

app/views/jobs/_form.html.slim
= form_for [@job] do |f|
  .form-group
  	= f.label "Job Title"
  	= f.text_field :title, placeholder: "Ruby on Rails Developer", class: "form-control"
  .form-group
  	= f.label "City"
  	= f.text_field :city, placeholder: "Los Angeles", class: "form-control"
  .form-group
  	= f.label "State"
  	= f.text_field :state, placeholder: "CA", class: "form-control"
  .form-group
    = f.label "Salary Range"
    = f.text_field :salary, placeholder: "60-80K", class: "form-control"    
  .form-group
  	= f.label "Job Description"
  	= f.text_area :description, class: "form-control"
  .col-md-12
    .row
      .col-md-6
        #statuses
        	= f.fields_for :statuses do |status|
        		== render 'status_fields', f: status
        br
        #jobfunctions
        	= f.fields_for :jobfunctions do |jobfunction|
        		== render 'jobfunction_fields', f: jobfunction
      .col-md-6
        #experience
          = f.fields_for :experiences do |experience|
            == render 'experience_fields', f: experience
        br
        #employment_type
          = f.fields_for :employment_types do |et|
            == render 'employment_type_fields', f: et  
  .col-md-offset-5.col-md-6
    .row
  	  = f.submit

app/views/jobs/_jobfunction_fields.html.slim
.nested-fields
	.field
	  = f.label "Job Function"
    = collection_select(:job, :jobfunction_id, Jobfunction.all, :id, :name)

app/views/jobs/_skill_fields.html.slim
.nested-fields
	.field
	  = f.label :name, class: "control-label"
    = collection_select(:job, :skill_id, Skill.all, :id, :name)

app/views/jobs/_status_fields.html.slim
.nested-fields
	.field
	  = f.label "Job Status"
    = collection_select(:job, :status_id, Status.all, :id, :name)

app/views/jobs/edit.html.slim
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.slim
.container
	.row
		.col-md-12.col-md-offset-4
			h1 See Current Job Postings
	.row
		.col-md-8.col-md-offset-1
			- @jobs.each do |j| 
				p
					= j.title
					br
					= j.city
					br
					= j.state
					br
					= j.description.truncate_words(10)
					br
					= link_to "Find Out More Information About This Job", job_path(j)

app/views/jobs/new.html.slim
.container.signup
	.col-md-offset-4.col-md-4
		h2 Create A New Job
	.row
	  .col-md-offset-2.col-md-8
	    == render 'form'

app/views/jobs/show.html.slim
.container
  .row
    .col-md-6.col-md-offset-4
      h2=@job.title
      br
  .row
    .col-md-12
      p=@job.description
.container
  .row
    .col-md-12
      .row.jobdivide
        .col-md-6.skill1divide
          .row
            .col-md-12.col-md-offset-4
              i.fa.fa-tachometer.fa-3x
          .row
            .col-md-6
              h4 Salary
              i.fa.fa-usd=@job.salary
            .col-md-6
              h4 City
              =@job.city
              h4 State
              =@job.state
        .col-md-6
          .row
            .col-md-12.col-md-offset-4
              i.fa.fa-briefcase.fa-3x
          .row
            .col-md-12
              h4 Job Function
              =@job.jobfunction.name
              h4 Employment Type
              =@job.employment_type.name
      .row.jobdivide
        .col-md-6
          .row
            .col-md-12.col-md-offset-4
              i.fa.fa-wrench.fa-3x
          .row
            .col-md-12
              i.fa.fa-check-circle-o.fa-lg=@job.skills.name
        .col-md-6.skill2divide
          .row
            .col-md-12.col-md-offset-4
              i.fa.fa-university.fa-3x
          .row
            .col-md-12
              h4 Company
              =link_to @job.company.name, company_path
              h4 Description
              =@job.company.description
              h4 Sector
              =@job.company.sector.name 
              br

app/views/users/_address_fields.html.slim
.nested-fields
	.field
		= f.label :address1, class: "control-label"
		= f.text_field :address1, class: "form-control"
	.field
		= f.label :address2, class: "control-label"
		= f.text_field :address2, class: "form-control"
	.field
		= f.label :city, class: "control-label"
		= f.text_field :city, class: "form-control"
	.field
		= f.label :state, class: "control-label"
		= f.text_field :state, class: "form-control"
	.field
		= f.label :zip, class: "control-label"
		= f.number_field :zip, class: "form-control"

app/views/users/_business_fields.html.slim
= form_for @user do |f|
  .form-group
    = f.label :first_name, class: "control-label"
    = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name, class: "control-label"
    = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email, class: "control-label" 
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password, class: "control-label"
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, class: "control-label"
    = f.password_field :password_confirmation, class: "form-control"
  .form-group
    = f.label @business_message, class: "control-label"
    = f.check_box :business, "1"
  div
    = f.submit @submit_message, class: "btn btn-primary"
        

app/views/users/_business_form.html.slim
= form_for @user do |f|
  .form-group
    = f.label :first_name, class: "control-label"
    = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name, class: "control-label"
    = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email, class: "control-label" 
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password, class: "control-label"
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, class: "control-label"
    = f.password_field :password_confirmation, class: "form-control"
  .form-group
    = f.label @business_message, class: "control-label"
    = f.check_box :business, "1"
  div
    = f.submit @submit_message, class: "btn btn-primary"
        

app/views/users/_company_show.html.slim
- if @company
	  = link_to "View Company Profile Page", company_path(@company), class: 'a btn btn-info'
	  = link_to "Edit Company Profile", edit_company_path(@company), class: 'a btn btn-success'
- else
	= link_to "Add A Company", new_company_path

app/views/users/_company_user_edit.html.slim
.col-md-offset-2.col-md-8
  = form_for @user do |f|
    h1 User Information
    #userinfo
    .form-group
      = f.label :first_name, class: "control-label"
      = f.text_field :first_name, class: "form-control"
    .form-group
      = f.label :last_name, class: "control-label"
      = f.text_field :last_name, class: "form-control"
    .form-group
      = f.label :email, class: "control-label" 
      = f.text_field :email, class: "form-control"
    .form-group
      = f.label :password, class: "control-label"
      = f.password_field :password, class: "form-control"
    .form-group
      = f.label :password_confirmation, class: "control-label"
      = f.password_field :password_confirmation, class: "form-control"
    h1 Address
    #address
    = f.fields_for :address do |a|
      == render 'address_fields', f: a
    br    
    = f.submit @submit_message, class: "btn btn-primary"

app/views/users/_education_fields.html.slim
.nested-fields
	.field
		= f.label :school_name, class: "control-label"
		= f.text_field :school_name, class: "form-control"
	.field
		= f.label :degree_name, class: "control-label"
		= f.text_field :degree_name, class: "form-control"
	.field
		= f.label :field_of_study, class: "control-label"
		= f.text_field :field_of_study, class: "form-control"
	.field
		= f.label "Start Year", class: "control-label"
		= f.date_select :yr_attended_from, class: "form-control"
	.field
		= f.label "End Year", class: "control-label"
		= f.date_select :yr_attended_to, class: "form-control"
	.field
		= f.label :description, class: "control-label"
		= f.text_area :description, class: "form-control"
	= link_to_remove_association "Remove Education", f

app/views/users/_form.html.slim
.col-md-offset-2.col-md-8
  = form_for @user do |f|
    h1 User Information
    #userinfo
    .form-group
      = f.label :first_name, class: "control-label"
      = f.text_field :first_name, class: "form-control"
    .form-group
      = f.label :last_name, class: "control-label"
      = f.text_field :last_name, class: "form-control"
    .form-group
      = f.label :email, class: "control-label" 
      = f.text_field :email, class: "form-control"
    .form-group
      = f.label :password, class: "control-label"
      = f.password_field :password, class: "form-control"
    .form-group
      = f.label :password_confirmation, class: "control-label"
      = f.password_field :password_confirmation, class: "form-control"
    h1 Address
    #address
    = f.fields_for :address do |a|
      == render 'address_fields', f: a  
    h1 Military Experience
    #military_experience
    = f.fields_for :military_experience do |me|
      == render 'military_experience_fields', f: me
    h1 Education
    #educations
    = f.fields_for :educations do |education|
      == render 'education_fields', f: education
    h1 Work History
    #work_histories
    = f.fields_for :work_histories do |work_history|
      == render 'work_history_fields', f: work_history
    h1 Skills
    #skills
    = f.fields_for :skills do |skill|
      == render 'skill_fields', f: skill
    div
     = f.submit @submit_message, class: "btn btn-primary"
     = link_to "Delete your profile!", :user, method: :delete, data: { confirm: "Are you sure you want to delete your profile?" }, :class => 'btn btn-warning'

app/views/users/_military_experience_fields.html.slim
.nested-fields
  .field
    = f.label :branch, class: "control-label"
    = f.text_field :branch, class: "form-control"
  .field
    = f.label :mos, class: "control-label"
    = f.text_field :mos, class: "form-control"
  .field
    = f.label "Served From", class: "control-label"
    = f.date_select :start_date, class: "form-control"
  .field
    = f.label "Served To", class: "control-label"
    = f.date_select :end_date, class: "form-control"

app/views/users/_skill_fields.html.slim
.nested-fields
	.field
		= f.label "Skill", class: "control-label"
		= f.text_field :name, class: "form-control"
	= link_to_remove_association "Remove Work History", f

app/views/users/_veteran_show.html.slim
h3 Military Experience
table
	tr
		th Start Date
		th End Date
		th Branch 
		th MOS
	tr
	- unless @user.military_experience.blank?
		td= @user.military_experience.start_date.strftime("%m-%d-%Y")
		td= @user.military_experience.end_date.strftime("%m-%d-%Y")
		td= @user.military_experience.branch
		td= @user.military_experience.mos
	- else 
		= link_to "Add Military Experience", edit_user_path(@user)
h3 Education
- unless @user.educations.blank?
	- @user.educations.each do |e|
		= e.school_name.upcase
		br 
		= "#{e.degree_name}, #{e.field_of_study}"
		br
		= "(#{e.yr_attended_from.strftime("%Y")} - #{e.yr_attended_to.strftime("%Y")})"
		p= e.description
- else
	= link_to " Add Education", edit_user_path(@user)
h3 Work History
- unless @user.work_histories.blank?
	- @user.work_histories.each do |wk|
		= wk.company_name.upcase
		br
		= "#{wk.job_title}"
		br
		= "worked from #{wk.start_date.strftime("%Y")} - #{wk.end_date.strftime("%Y")}"
		br
		= wk.description
		p
- else
	= link_to "Add Work History", edit_user_path(@user)
h3 Skills 
- unless @user.skills.blank?
	- @user.skills.each do |sk|
		ul
	  	li= sk.name
- else	  	
	= link_to "Add Skills", edit_user_path(@user)

app/views/users/_work_history_fields.html.slim
.nested-fields
	.field
		= f.label :company_name, class: "control-label"
		= f.text_field :company_name, class: "form-control"
	.field
		= f.label :job_title, class: "control-label"
		= f.text_field :job_title, class: "form-control"
	.field
		= f.label :location, class: "control-label"
		= f.text_field :location, class: "form-control"
	.field
		= f.label "Start Date"
		= f.date_field :start_date, class: "form-control"
	.field
		= f.label "End Year"
		= f.date_field :end_date, class: "form-control"
	.field
		= f.label :description, class: "control-label"
		= f.text_area :description, class: "form-control"

app/views/users/edit.html.slim
.container
  .row
    .col-md-10
    / this will show switch from veteran to company depending on which is logged in. 
    - if current_user_is_veteran?
      == render 'form'
    - else
      == render 'company_user_edit'
    .col-md-2
      - unless @user.errors.full_messages.empty?
        h1.text-center Oops!
        ul.list-group
          - @user.errors.full_messages.each do |msg|
            li.list-group-items.list-group-item-danger
              = msg

app/views/users/new.html.slim
.pad-section
	.container
	  .row
			.col-md-offset-3.col-md-8
				.col-md-6
					button.btn.btn-primary.btn-lg data-target="#veteranModal" data-toggle="modal" type="button" 
					  | Sign Up As A Veteran
					/! Modal
					#veteranModal.modal.fade aria-hidden="true" aria-labelledby="veteranModalLabel" role="dialog" tabindex="-1" 
					  .modal-dialog
					    .modal-content
					      .modal-header
					        button.close aria-label="Close" data-dismiss="modal" type="button" 
					          span aria-hidden="true"  &times;
					        h4#veteranModalLabel.modal-title Veteran Sign Up
					      .modal-body
									= form_for @user do |f|
									  .form-group
									    = f.label :first_name, class: "control-label"
									    = f.text_field :first_name, class: "form-control"
									  .form-group
									    = f.label :last_name, class: "control-label"
									    = f.text_field :last_name, class: "form-control"
									  .form-group
									  	= f.label :avatar, "Add a profile image"
			    						= f.file_field :avatar 
									  .form-group
									    = f.label :email, class: "control-label" 
									    = f.text_field :email, class: "form-control"
									  .form-group
									    = f.label :password, class: "control-label"
									    = f.password_field :password, class: "form-control"
									  .form-group
									    = f.label :password_confirmation, class: "control-label"
									    = f.password_field :password_confirmation, class: "form-control"
									  .form-group
									    = f.hidden_field :business, value: "0"
									  div
									    = f.submit @submit_message, class: "btn btn-primary"
					      .modal-footer
					        button.btn.btn-default data-dismiss="modal" type="button"  Close
				.col-md-6
					button.btn.btn-primary.btn-lg data-target="#companyModal" data-toggle="modal" type="button" 
					  | Sign Up As A Company
					/! Modal
					#companyModal.modal.fade aria-hidden="true" aria-labelledby="companyModalLabel" role="dialog" tabindex="-1" 
					  .modal-dialog
					    .modal-content
					      .modal-header
					        button.close aria-label="Close" data-dismiss="modal" type="button" 
					          span aria-hidden="true"  &times;
					        h4#companyModalLabel.modal-title Company Sign Up
					      .modal-body
									= form_for @user do |f|
									  .form-group
									    = f.label :first_name, class: "control-label"
									    = f.text_field :first_name, class: "form-control"
									  .form-group
									    = f.label :last_name, class: "control-label"
									    = f.text_field :last_name, class: "form-control"
									  .form-group
									    = f.label :email, class: "control-label" 
									    = f.text_field :email, class: "form-control"
									  .form-group
									    = f.label :password, class: "control-label"
									    = f.password_field :password, class: "form-control"
									  .form-group
									    = f.label :password_confirmation, class: "control-label"
									    = f.password_field :password_confirmation, class: "form-control"
									  .form-group
									  	= f.label "Verify you are creating an account on behalf of a Business/Company"
									    = f.check_box :business, value: "1"
									  div
									    = f.submit @submit_message, class: "btn btn-primary"
					      .modal-footer
					        button.btn.btn-default data-dismiss="modal" type="button"  Close	        

app/views/users/show.html.slim
.container
  section
    .row
      .col-md-4
        img.img-rounded.img-responsive
          - if @user.avatar.url(:small).present?
            = image_tag @user.avatar.url(:small)
          - else
            img src="https://s3-us-west-1.amazonaws.com/theveteranproject/default_user_image.png" /
        br/
        br/     
        h5 
          strong Email
        - if @user.email.present?
          =@user.email
        - else
          p Email Not Available
        h5
          strong Phone Number
        - if @user.phone_number.present?
          =@user.phone_number
        - else
          p Phone Number Not Available
        br/
        = link_to "Update Your Account", edit_user_path(@user), class: 'a btn btn-success'
        br/
        - if current_user_is_veteran?
          h5 Verify Your Veteran Status with ID.me
          a.login-trigger href="#" 
            img alt=("Verify your military affiliation with ID.me") src="https://s3.amazonaws.com/idme/buttons/troop_red_rnd_40.png"
        - else
          h5
            strong Add A New Job
          = link_to "Add A Job", new_job_path, class: 'a btn btn-info'         
      .col-md-8
        .alert.alert-info
          h2=@name
          p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
        .col-md-12
          - if current_user_is_veteran?
            == render 'veteran_show'
          - else
            == render 'company_show'